### ISSUE TITLE
directory missing from npm module 

### ISSUE THREAD

**Issue by gschrader** [dpjanes/node-iotdb#1]
The files in node-iotdb/helpers didn't seem to get installed for me when I did a `sudo npm -g install iotdb`

**Comment by dpjanes** [comment]
My apologies - try now.

Note that we're making a major major overhaul to IOTDB which should be ready in about two weeks, making it much much lighter and easier to add new things. Everything you write using it will continue to work tho!

**Comment by gschrader** [comment]
Thanks yes that seems to be better now.  Ok I'll maybe put this aside for now then, I'm a little lost trying to get my smartthings hooked up, I'll wait until things have settled down.

**Comment by dpjanes** [comment]
Feel free to ask questions. You can use iotdb-smartthings without IOTDB.

**Comment by gschrader** [comment]
Thanks, I see my smartthings events are actually being sent to the mqtt bridge, so that gives me enough to play with for now.  Initially I wasn't sure what how these projects related to each other, I think I'm understanding it a bit now.
